APP_TITLE = "ReviewTrash"

STATUS_INIT = "Create a project or open an existing project file."
STATUS_NO_DIALOGUE = "No Dialogue lines were found in the ASS file."
STATUS_NO_MATCHED_ENTRY = "No entry matched the requested condition."
STATUS_AUTOSAVE_RESTORED = "Autosave content restored."
STATUS_REPLACE_CURRENT_NO_MATCH = "No replaceable match was found in the current entry."
STATUS_REPLACE_ALL_NO_MATCH = "No entries matched the replace-all condition."
STATUS_REPLACE_ALL_DONE = "Replace all completed: {changed_rows} rows, {replace_hits} matches."
STATUS_SAVED = "Save succeeded, backup created: {backup_name} ({backup_path})"
STATUS_PROJECT_OPENED = "Project opened: {project_path}"
STATUS_PROJECT_INITIALIZED = "Project initialized: {project_path}"
STATUS_LOADING_IMAGE = "Loading image..."
STATUS_NO_SUBTITLE = "No subtitle loaded"
STATUS_IMAGE_LOAD_FAILED = "Image load failed: {error}"
STATUS_NO_MATCHING_IMAGE = "No matching image found\nExpected: {expected}"
STATUS_PROGRESS = (
    "Current {current}/{total} | Reviewed {reviewed} | Missing {missing} | Unsaved {unsaved}"
)

ERR_TITLE = "Error"
ERR_OPEN_ASS_FIRST = "Open an ASS subtitle file first."
ERR_FIND_TEXT_REQUIRED = "Enter text to find first."
ERR_READ_ASS_FAILED = "Failed to read ASS file: {exc}"
ERR_READ_PROJECT_FAILED = "Failed to read project file or file format is invalid."
ERR_ASS_NOT_FOUND = "ASS file referenced by the project does not exist: {ass_path}"
ERR_IMAGE_DIR_NOT_FOUND = "Image directory referenced by the project does not exist: {image_dir}"
ERR_IMAGE_DIR_LOAD_FAILED = "Failed to load image directory: {exc}"
ERR_PROJECT_IMAGE_DIR_LOAD_FAILED = "Failed to load project image directory: {exc}"
ERR_PROJECT_STATE_SAVE_FAILED = "Failed to save project state: {exc}"
ERR_SAVE_FAILED = "Save failed: {exc}"
ERR_ASS_FILE_NOT_FOUND = "ASS file does not exist: {ass_path}"
ERR_IMAGE_DIRECTORY_NOT_FOUND = "Image directory does not exist: {image_dir}"
ERR_PROJECT_CONFIG_DIR_NOT_FOUND = "Project config directory does not exist: {project_dir}"

DLG_AUTOSAVE_FOUND_TITLE = "Autosave Found"
DLG_AUTOSAVE_FOUND_TEXT = "Unsaved autosave data was found. Restore it now?"
DLG_UNSAVED_TITLE = "Unsaved Changes"
DLG_UNSAVED_TEXT = "There are unsaved subtitle changes. Exit anyway?"

UI_PROGRESS_ZERO = "Progress 0/0"
UI_STATS_ZERO = "Missing 0 | Unsaved 0"
UI_PROGRESS = "Progress {reviewed}/{total} ({progress}%)"
UI_STATS = "Missing {missing} | Unsaved {unsaved}"

LBL_SUBTITLE_INDEX = "Subtitle Index"
LBL_ISSUES = "Issues"
LBL_IMAGE_PREVIEW = "Image Preview"
LBL_NO_IMAGE = "No image loaded"
LBL_SUBTITLE_TEXT = "Subtitle Text"
LBL_ORIGINAL = "Original"
LBL_DIFF = "Diff Highlight"

ACT_NEW_PROJECT = "New Project"
ACT_OPEN_PROJECT = "Open Project"
ACT_SAVE_SUBTITLE = "Save Subtitle"

BTN_PREVIOUS = "Previous"
BTN_NEXT = "Next"
BTN_TOGGLE_REVIEWED = "Toggle Reviewed (Ctrl+R)"
BTN_AUTO_REVIEW = "Auto-mark current as reviewed when moving next"
BTN_NEXT_UNREVIEWED = "Next Unreviewed (F8)"
BTN_NEXT_MODIFIED = "Next Modified (F9)"
BTN_REPLACE = "Replace"
BTN_BROWSE = "Browse..."
BTN_REPLACE_CURRENT = "Replace Current"
BTN_REPLACE_ALL = "Replace All"
BTN_CLOSE = "Close"

DLG_NEW_PROJECT_TITLE = "New Project"
DLG_REPLACE_TITLE = "Replace"
DLG_SELECT_ASS = "Select ASS Subtitle File"
DLG_SELECT_PNG_DIR = "Select PNG Folder"
DLG_SELECT_PROJECT_DIR = "Select Project Config Directory"
DLG_OPEN_PROJECT = "Open Project File"
DLG_OPEN_PROJECT_FILTER = "Subtitle Project (*.subtitle-project.json);;JSON Files (*.json)"
DLG_ASS_FILTER = "ASS Files (*.ass)"

LBL_ASS_SUBTITLE = "ASS Subtitle"
LBL_IMAGE_FOLDER = "Image Folder"
LBL_PROJECT_CONFIG_DIR = "Project Config Dir"
LBL_FIND = "Find"
LBL_REPLACE = "Replace"
LBL_REPLACE_WITH = "Replace with"

ISSUE_PARSE = "[Parse] {message}"
ISSUE_MISSING = "[Missing] Row {row} has no matching image"
